services:
  - type: web
    name: Danini-backend
    env: docker
    plan: free
    repo: https://github.com/Da-ni-ni/Back-End
    region: singapore
    branch: develop
    dockerfilePath: ./Dockerfile

    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/java
      - key: DB_URL
        value: jdbc:mysql://localhost:3306/danini_db?serverTimezone=Asia/Seoul
      - key: DB_USERNAME
        value: mooyou
      - key: DB_PASSWORD
        value: mooyouA2
      - key: JWT_SECRET
        value: UEFQNDFSdWJSX2E4Mm1nVFd6U1NnZDg0UmNSM1NnX1FRU2Jzdm1kNFp4bw==
      - key: JWT_EXPIRATION_MS
        value: 3600000
