services:
  - type: web
    name: Danini-backend
    env: docker
    plan: free
    repo: https://github.com/Da-ni-ni/Back-End
    region: singapore
    branch: develop
    buildCommand: ./gradlew build -x test
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/java
