spring:
  application:
    name: Da-ni-ni

  datasource:
    url: jdbc:mysql://localhost:3306/danini_db?serverTimezone=Asia/Seoul
    username: mooyou
    password: mooyouA2

  jackson:
    time-zone: Asia/Seoul

  jpa:
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 10
        format_sql: true

    hibernate:
      ddl-auto: create
      show-sql: true
      default_batch_fetch_size: 100

  main:
    allow-bean-definition-overriding: true

  # jwt:
  #   secret:
  #   access-expiration:

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # aws:
  #   credentials:
  #     access-key: YOUR_AWS_ACCESS_KEY
  #     secret-key: YOUR_AWS_SECRET_KEY
  #   s3:
  #     bucket: your-bucket-name
  #     region: ap-northeast-2
  #   stack:
  #     auto: false